### ISSUE TITLE
python编码风格

### ISSUE THREAD

**Issue by momnon** [BuryLoveGroup/foothold#20]
1 .使用空格来表示缩进,而不要用tab
2. 和语法相关的每一层都用4个空格来表示
3. 每行的字符数不超过79
4. 对于占据多行的长表达式来说,除了首行之外的其余各行都应该在通常的缩进级别之上再加上4个空格
5. 文件中的函数与类之间应该用两个空格隔开
6. 在同一个类中,个方法之间应该用一个空行隔开
7. 在使用下标来列表元素,调用函数或给关键字参数赋值的时候,不要在两旁添加空格.(**e.g**: a[ 1 ],sys. version, a(b  = 1))
8. 为变量赋值的时候,赋值符号的左侧和右侧应该各自写上一个空格,而且只写一个就好.

**Comment by momnon** [comment]
* 编写Python程序时,不要一昧追求过于紧凑的写法,那样会写出非常复杂的表达式,这个时候应该考虑将其拆成小块,并把这些逻辑移入辅助函数中(辅助函数一定要写的简洁明了,而不是滥用表达式)

**Comment by HanShuiShiW** [comment]
大汉，你最近在研究python啊
